/**
 * @author mikelownds
 */
package questions
{
	public class QuestionResponses
	{
		// Load Images
		{
		[Embed(source="question_responses/apple.png")] public var apple:Class;
		[Embed(source="question_responses/applejuice.png")] public var applejuice:Class;
		[Embed(source="question_responses/asparagus.png")] public var asparagus:Class;
		[Embed(source="question_responses/baking.png")] public var baking:Class;
		[Embed(source="question_responses/banana.png")] public var banana:Class;
		[Embed(source="question_responses/basketball.png")] public var basketball:Class;
		[Embed(source="question_responses/biking.png")] public var biking:Class;
		[Embed(source="question_responses/broccoli.png")] public var broccoli:Class;
		[Embed(source="question_responses/brusselssprouts.png")] public var brusselssprouts:Class;
		[Embed(source="question_responses/cabbage.png")] public var cabbage:Class;
		[Embed(source="question_responses/candybar.png")] public var candybar:Class;
		[Embed(source="question_responses/caramel_apple.png")] public var caramel_apple:Class;
		[Embed(source="question_responses/carrot.png")] public var carrot:Class;
		[Embed(source="question_responses/cauliflower.png")] public var cauliflower:Class;
		[Embed(source="question_responses/cheese.png")] public var cheese:Class;
		[Embed(source="question_responses/chocolateshake.png")] public var chocolateshake:Class;
		[Embed(source="question_responses/cinnamon_raisin_bread.png")] public var cinnamon_raisin_bread:Class;
		[Embed(source="question_responses/coloring.png")] public var coloring:Class;
		[Embed(source="question_responses/crackers.png")] public var crackers:Class;
		[Embed(source="question_responses/cucumber.png")] public var cucumber:Class;
		[Embed(source="question_responses/dairy.png")] public var dairy:Class;
		[Embed(source="question_responses/dancing.png")] public var dancing:Class;
		[Embed(source="question_responses/egg.png")] public var egg:Class;
		[Embed(source="question_responses/energy_drinks.png")] public var energy_drinks:Class;
		[Embed(source="question_responses/french_fries.png")] public var french_fries:Class;
		[Embed(source="question_responses/fruitpunch.png")] public var fruitpunch:Class;
		[Embed(source="question_responses/fruits.png")] public var fruits:Class;
		[Embed(source="question_responses/fruits_and_vegetables.png")] public var fruits_and_vegetables:Class;
		[Embed(source="question_responses/grains.png")] public var grains:Class;
		[Embed(source="question_responses/granola_bar.png")] public var granola_bar:Class;
		[Embed(source="question_responses/grape_drink.png")] public var grape_drink:Class;
		[Embed(source="question_responses/grapes.png")] public var grapes:Class;
		[Embed(source="question_responses/hockey.png")] public var hockey:Class;
		[Embed(source="question_responses/hop.png")] public var hop:Class;
		[Embed(source="question_responses/hulahoop.png")] public var hulahoop:Class;
		[Embed(source="question_responses/imagination.png")] public var imagination:Class;
		[Embed(source="question_responses/juice.png")] public var juice:Class;
		[Embed(source="question_responses/jump.png")] public var jump:Class;
		[Embed(source="question_responses/jumping_jacks.png")] public var jumping_jacks:Class;
		[Embed(source="question_responses/jumprope.png")] public var jumprope:Class;
		[Embed(source="question_responses/lemonade.png")] public var lemonade:Class;
		[Embed(source="question_responses/meat.png")] public var meat:Class;
		[Embed(source="question_responses/milk.png")] public var milk:Class;
		[Embed(source="question_responses/mushrooms.png")] public var mushrooms:Class;
		[Embed(source="question_responses/orange.png")] public var orange:Class;
		[Embed(source="question_responses/pear.png")] public var pear:Class;
		[Embed(source="question_responses/playing_video_games.png")] public var playing_video_games:Class;
		[Embed(source="question_responses/plum.jpg")] public var plum:Class;
		[Embed(source="question_responses/pop.png")] public var pop:Class;
		[Embed(source="question_responses/potato_chips.png")] public var potato_chips:Class;
		[Embed(source="question_responses/pushups.png")] public var pushups:Class;
		[Embed(source="question_responses/raisins.png")] public var raisins:Class;
		[Embed(source="question_responses/slushie.png")] public var slushie:Class;
		[Embed(source="question_responses/sports_drink.png")] public var sports_drink:Class;
		[Embed(source="question_responses/water.png")] public var water:Class;
		[Embed(source="question_responses/raspberries.png")] public var raspberries:Class;
		[Embed(source="question_responses/reading.png")] public var reading:Class;
		[Embed(source="question_responses/rice.png")] public var rice:Class;
		[Embed(source="question_responses/running.png")] public var running:Class;
		[Embed(source="question_responses/sit.png")] public var sit:Class;
		[Embed(source="question_responses/situps.png")] public var situps:Class;
		[Embed(source="question_responses/sliceofbread.png")] public var sliceofbread:Class;
		[Embed(source="question_responses/soccer.png")] public var soccer:Class;
		[Embed(source="question_responses/softball.png")] public var softball:Class;
		[Embed(source="question_responses/spinach.png")] public var spinach:Class;
		[Embed(source="question_responses/squash.png")] public var squash:Class;
		[Embed(source="question_responses/strawberries.png")] public var strawberries:Class;
		[Embed(source="question_responses/stretching.png")] public var stretching:Class;
		[Embed(source="question_responses/sweet_rolls.png")] public var sweet_rolls:Class;
		[Embed(source="question_responses/sweet_tea.png")] public var sweet_tea:Class;
		[Embed(source="question_responses/swimming.png")] public var swimming:Class;
		[Embed(source="question_responses/tag.png")] public var tag:Class;
		[Embed(source="question_responses/tomato.png")] public var tomato:Class;
		[Embed(source="question_responses/veggiejuice.png")] public var veggiejuice:Class;
		[Embed(source="question_responses/walk.png")] public var walk:Class;
		[Embed(source="question_responses/watching_tv.png")] public var watching_tv:Class;
		[Embed(source="question_responses/weightbearing.png")] public var weightbearing:Class;
		[Embed(source="question_responses/wheat_toast.png")] public var wheat_toast:Class;
		[Embed(source="question_responses/yoga.png")] public var yoga:Class;
		}
		
		// Setup Image Responses
		{
		public var _apple:Response = new Response( "Apple", new apple() );
		public var _applejuice:Response = new Response( "Apple Juice", new applejuice() );
		public var _asparagus:Response = new Response( "Asparagus", new asparagus() );
		public var _baking:Response = new Response( "Baking", new baking() );
		public var _banana:Response = new Response( "Banana", new banana() );
		public var _basketball:Response = new Response( "Basketball", new basketball() );
		public var _biking:Response = new Response( "Biking", new biking() );
		public var _broccoli:Response = new Response( "Broccoli", new broccoli() );
		public var _brusselssprouts:Response = new Response( "Brussels Sprouts", new brusselssprouts() );
		public var _cabbage:Response = new Response( "Cabbage", new cabbage() );
		public var _candybar:Response = new Response( "Candy Bar", new candybar() );
		public var _caramel_apple:Response = new Response( "Caramel Apple", new caramel_apple() );
		public var _carrot:Response = new Response( "Carrot", new carrot() );
		public var _cauliflower:Response = new Response( "Cauliflower", new cauliflower() );
		public var _cheese:Response = new Response( "Cheese", new cheese() );
		public var _chocolateshake:Response = new Response( "Chocolate Shake", new chocolateshake() );
		public var _cinnamon_raisin_bread:Response = new Response( "Cinnamon Raisin Bread", new cinnamon_raisin_bread() );
		public var _coloring:Response = new Response( "Coloring", new coloring() );
		public var _crackers:Response = new Response( "Crackers", new crackers() );
		public var _cucumber:Response = new Response( "Cucumber", new cucumber() );
		public var _dairy:Response = new Response( "Dairy", new dairy() );
		public var _dancing:Response = new Response( "Dancing", new dancing() );
		public var _egg:Response = new Response( "Egg", new egg() );
		public var _energy_drinks:Response = new Response( "Energy Drinks", new energy_drinks() );
		public var _french_fries:Response = new Response( "French Fries", new french_fries() );
		public var _fruitpunch:Response = new Response( "Fruit Punch", new fruitpunch() );
		public var _fruits:Response = new Response( "Fruits", new fruits() );
		public var _fruits_and_vegetables:Response = new Response( "Fruits and Vegetables", new fruits_and_vegetables() );
		public var _grains:Response = new Response( "Grains", new grains() );
		public var _granola_bar:Response = new Response( "Granola Bar", new granola_bar() );
		public var _grape_drink:Response = new Response( "Grape Drink", new grape_drink() );
		public var _grapes:Response = new Response( "Grapes", new grapes() );
		public var _hockey:Response = new Response( "Hockey", new hockey() );
		public var _hop:Response = new Response( "Hop", new hop() );
		public var _hulahoop:Response = new Response( "Hulahoop", new hulahoop() );
		public var _imagination:Response = new Response( "Imagination", new imagination() );
		public var _juice:Response = new Response( "Juice", new juice() );
		public var _jump:Response = new Response( "Jump", new jump() );
		public var _jumping_jacks:Response = new Response( "Jumping Jacks", new jumping_jacks() );
		public var _jumprope:Response = new Response( "Jump Rope", new jumprope() );
		public var _lemonade:Response = new Response( "Lemonade", new lemonade() );
		public var _meat:Response = new Response( "Meat", new meat() );
		public var _milk:Response = new Response( "Milk", new milk() );
		public var _mushrooms:Response = new Response( "Mushrooms", new mushrooms() );
		public var _orange:Response = new Response( "Orange", new orange() );
		public var _pear:Response = new Response( "Pear", new pear() );
		public var _playing_video_games:Response = new Response( "Playing Video Games", new playing_video_games() );
		public var _plum:Response = new Response( "Plum", new plum() ); //JPG????
		public var _pop:Response = new Response( "Pop", new pop() );
	public var _soda:Response = new Response( "Soda", new pop() );
		public var _potato_chips:Response = new Response( "Potato Chips", new potato_chips() );
		public var _pushups:Response = new Response( "Pushups", new pushups() );
		public var _raisins:Response = new Response( "Raisins", new raisins() );
		public var _raspberries:Response = new Response( "Raspberries", new raspberries() );
		public var _reading:Response = new Response( "Reading", new reading() );
		public var _rice:Response = new Response( "Rice", new rice() );
		public var _running:Response = new Response( "Running", new running() );
		public var _sit:Response = new Response( "Sit", new sit() );
		public var _situps:Response = new Response( "Situps", new situps() );
		public var _sliceofbread:Response = new Response( "Slice of Bread", new sliceofbread() );
		public var _slushie:Response = new Response( "Slushie", new slushie() );
		public var _soccer:Response = new Response( "Soccer", new soccer() );
		public var _softball:Response = new Response( "Softball", new softball() );
		public var _spinach:Response = new Response( "Spinach", new spinach() );
		public var _sportsdrink:Response = new Response( "Sports Drink", new sports_drink() );
		public var _squash:Response = new Response( "Squash", new squash() );
		public var _strawberries:Response = new Response( "Strawberries", new strawberries() );
		public var _stretching:Response = new Response( "Stretching", new stretching() );
		public var _sweet_rolls:Response = new Response( "Sweet Rolls", new sweet_rolls() );
		public var _sweet_tea:Response = new Response( "Sweet Tea", new sweet_tea() );
		public var _swimming:Response = new Response( "Swimming", new swimming() );
		public var _tag:Response = new Response( "Tag", new tag() );
		public var _tomato:Response = new Response( "Tomato", new tomato() );
		public var _veggiejuice:Response = new Response( "Veggie Juice", new veggiejuice() );
		public var _walk:Response = new Response( "Walk", new walk() );
		public var _watching_tv:Response = new Response( "Watching TV", new watching_tv() );
		public var _water:Response = new Response( "Water", new water() );
		public var _weightbearing:Response = new Response( "Weight Bearing", new weightbearing() );
		public var _wheat_toast:Response = new Response( "Wheat Toast", new wheat_toast() );
		public var _yoga:Response = new Response( "Yoga", new yoga() );
		}
		
		// Text Responses
		{
		public var _Two_handfuls:Response = 	new Response( "Two handfuls" );
		public var _One_fist:Response = 	new Response( "One fist" );
		public var _Golf_Ball:Response = 	new Response( "Golf Ball" );
		public var _As_much_as_you_can_eat:Response = 	new Response( "As much as you can eat" );
		public var _Size_of_your_foot:Response = 	new Response( "Size of your foot" );
		public var _A_way_to_measure_food:Response = 	new Response( "A Way To Measure Food" );
		public var _Found_on_all_food_labels:Response = 	new Response( "Found On All Food Labels" );
		public var _Important_to_know_for_choosing_healthier_portions:Response = 	new Response( "Helpful For Choosing Healthier Sized Portions" );
		public var _All_of_these_choices:Response = 	new Response( "All of these choices!" );
		public var _Vitamins:Response = 	new Response( "Vitamins" );
		public var _Antioxidants:Response = 	new Response( "Antioxidants" );
		public var _Minerals:Response = 	new Response( "Minerals" );
		public var _Extra_Calories:Response = 	new Response( "Extra Calories" );
		public var _Extra_Fat:Response = 	new Response( "Extra Fat" );
		public var _Extra_Sugar:Response = 	new Response( "Extra Sugar" );
		public var _Sugar:Response = 	new Response( "Sugar" );
		public var _Fat:Response = 	new Response( "Fat" );
		public var _Our_heart_rate_increases:Response = 	new Response( "Heart rate increases" );
		public var _We_are_breathing_heavier:Response = 	new Response( "Breathing heavier" );
		public var _We_feel_warmer:Response = 	new Response( "Feel warmer" );
		public var _Air:Response = 	new Response( "Air" );
		public var _Iron:Response = 	new Response( "Iron" );
		public var _Oxygen:Response = 	new Response( "Oxygen" );
		public var _Eat_More:Response = 	new Response( "Eat More Of" );
		public var _Eat_Less:Response = 	new Response( "Eat Less Of" );
		public var _Eat_None:Response = 	new Response( "Eat None Of" );
		public var _Be_strong_and_healthy:Response = 	new Response( "Be healthy" );
		public var _Wake_up:Response = 	new Response( "Wake up" );
		public var _Fly:Response = 	new Response( "Fly" );
		public var _Read:Response = 	new Response( "Read" );
		public var _Fruits:Response = 	new Response( "Fruits" );
		public var _Protein:Response = 	new Response( "Protein" );
		public var _Vegetables:Response = 	new Response( "Vegetables" );
		public var _Dairy:Response = 	new Response( "Dairy" );
		public var _2_two:Response = 	new Response( "2 Servings" );
		public var _3_three:Response = 	new Response( "3 Servings" );
		public var _4_four:Response = 	new Response( "4 Servings" );
		public var _5_five:Response = 	new Response( "5 Servings" );
		public var _4_ounces:Response = 	new Response( "4 ounces" );
		public var _8_ounces:Response = 	new Response( "8 ounces" );
		public var _12_ounces:Response = 	new Response( "12 ounces" );
		public var _16_ounces:Response = 	new Response( "16 ounces" );
		public var _One_time_each_week:Response = 	new Response( "One time each week" );
		public var _One_time_each_month:Response = 	new Response( "One time each month" );
		public var _One_time_each_day:Response = 	new Response( "One time each day" );
		public var _One_time_each_year:Response = 	new Response( "One time each year" );
		public var _At_least_1_hour:Response = 	new Response( "At least 1 hour" );
		public var _At_least_30_minutes:Response = 	new Response( "At least 30 minutes" );
		public var _At_least_1_minute:Response = 	new Response( "At least 1 minute" );
		public var _At_least_2_hours:Response = 	new Response( "At least 2 hours" );
		public var _Feel_great:Response = 	new Response( "Feel great" );
		public var _Burn_extra_energy:Response = 	new Response( "Burn extra energy" );
		public var _Fall_asleep_faster:Response = 	new Response( "Sleep Better" /*"Fall asleep faster"*/ );
		public var _Half:Response = 	new Response( "Half" );
		public var _All:Response = 	new Response( "All" );
		public var _None:Response = 	new Response( "None" );
		public var _Almost_all:Response = 	new Response( "Almost all" );
		public var _Blood:Response = 	new Response( "Blood" );
		public var _Organs:Response = 	new Response( "Organs" );
		public var _Water:Response = 	new Response( "Water" );
		public var _Skin:Response = 	new Response( "Skin" );
		public var _Ice:Response = 	new Response( "Ice" );
		public var _Milk:Response = 	new Response( "Milk" );
		public var _1_cup_white_rice:Response = 	new Response( "1 cup white rice" );
		public var _1_slice_whole_wheat_bread:Response = 	new Response( "1 slice whole wheat bread" );
		public var _3_4_cups_whole_grain_pasta:Response = 	new Response( "¾ cups whole grain pasta" );
		public var _Cinnamon_roll:Response = 	new Response( "Cinnamon roll" );
		public var _2_eggs:Response = 	new Response( "2 eggs" );
		public var _1_4_cup_of_beans:Response = 	new Response( "¼ cup of beans" );
		public var _1_cup_of_almonds:Response = 	new Response( "1 cup of almonds" );
		public var _10_oz_steak:Response = 	new Response( "10 oz. steak" );
		public var _2_slices_of_cheese:Response = 	new Response( "2 slices of cheese" );
		public var _6_ounces_of_milk:Response = 	new Response( "6 ounces of milk" );
		public var _8_ounces_of_yogurt:Response = 	new Response( "8 ounces of yogurt" );
		public var _1_cup_of_ice_cream:Response = 	new Response( "1 cup of ice cream" );
		public var _1_slice_of_bread:Response = 	new Response( "1 slice of bread" );
		public var _1_egg:Response = 	new Response( "1 egg" );
		public var _1_cup_of_rice:Response = 	new Response( "1 cup of rice" );
		public var _1_4_cup_of_raisins:Response = 	new Response( "¼ cup of raisins" );
		public var _3_oz_of_meat:Response = 	new Response( "3 oz. of meat" );
		public var _1_2_c_of_rice:Response = 	new Response( "½ c. of rice" );
		public var _A_medium_size_fruit:Response = 	new Response( "A medium size fruit" );
		public var _Continue_sitting:Response = 	new Response( "Continue sitting" );
		public var _Walk_to_get_a_snack_and_sit_back_down:Response = 	new Response( "Eat A Snack" );
		public var _Jumping_Jacks:Response = 	new Response( "Jumping Jacks" );
		public var _Get_a_drink_of_water:Response = 	new Response( "Drink Water" );
		public var _3_oz_grilled_chicken_breast_no_skin_:Response = 	new Response( "3 oz. Grilled Chicken Breast" );
		public var _3_slices_of_bacon:Response = 	new Response( "3 slices of bacon" );
		public var _1_hot_dog:Response = 	new Response( "1 hot dog" );
		public var _Sour_Driblets:Response = 	new Response( "Sour Driblets" );
		public var _5_minutes:Response = 	new Response( "5 minutes" );
		public var _10_minutes:Response = 	new Response( "10 minutes" );
		public var _20_minutes:Response = 	new Response( "20 minutes" );
		public var _1_hour:Response = 	new Response( "1 hour" );
		
		//public var _french_fries:Response = new Response( "French Fries" );
		public var _be_more_popular:Response = new Response( "Be More Popular" );
		public var _read_better:Response = new Response( "Read Better" );
		//public var _sportsdrink:Response = new Response( "Sports Drink" );
		//public var _slushie:Response = new Response( "Slushie" );
		public var _Swimming:Response = new Response( "Swimming" );
		public var _Bike_Riding:Response = new Response( "Bike Riding" );
		public var _Jump_Roping:Response = new Response( "Jump Roping" );
		public var _Stretching:Response = new Response( "Stretching" );
		public var _muscles:Response = new Response( "Muscles" );
		public var _bones:Response = new Response( "Bones" );
		public var _grains_copy:Response = new Response( "Grains" );
		public var _in_grocery_stores:Response = new Response(  "in grocery stores" );
		public var _in_the_ground:Response = new Response(  "in the ground" );
		public var _on_trees:Response = new Response(  "on trees" );
		public var _and_come_down_from_the_sky:Response = new Response(  "In the sky" );
		
		public var _reading_a_book:Response = new Response( "Reading a Book" );
		public var _playing_a_video_game:Response = new Response( "Playing a Video Game" );
		public var _playing_tag:Response = new Response( "Playing Tag" );
		public var _Coloring:Response = new Response( "Coloring" );
		
		public var _Read2:Response = new Response( "Read" );
		public var _Color:Response = new Response( "Color" );
		public var _Stretch:Response = new Response( "Stretch" );
		public var _Watch_TV:Response = new Response( "Watch TV" );
		public var _Eat:Response = new Response( "Eat" );
		
		public var _A_Small_Amount:Response = new Response( "A Small Amount" );
		public var _1_Large_Bowl_of_Popcorn:Response = new Response( "1 Large Bowl of Popcorn" );
		public var _2_Donuts:Response = new Response( "2 Donuts" );
		public var _7_days:Response = new Response( "7 days" );
		public var _6_days:Response = new Response( "6 days" );
		public var _5_days:Response = new Response( "5 days" );
		public var _4_days:Response = new Response( "4 days" );
		public var _3_Cups:Response = new Response( "3 Cups" );
		public var _4_Cups:Response = new Response( "4 Cups" );
		public var _5_Cups:Response = new Response( "5 Cups" );
		public var _6_Cups:Response = new Response( "6 Cups" );
		
		}
		
		public function QuestionResponses()
		{
		}
	}

}